
# COMANDOS PARA USAR EN LA CONSOLA ADENTRO DE MYSQL ASI: mysql>

# Crear y usar base de datos
source C:/setup_database/empresa/scripts/create_database.sql;

# Eliminar base de datos
source C:/setup_database/empresa/scripts/delete_database.sql;

# Iniciar base de datos
source C:/setup_database/empresa/scripts/init_database.sql;

# Insertrar registros en la base de datos
source C:/setup_database/empresa/scripts/inserts_database.sql;